name: nerdstore

x-common-variables: &common-variables
    ASPNETCORE_ENVIRONMENT: Docker
    ASPNETCORE_URLS: https://+:443;http://+:80
    ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
    ASPNETCORE_Kestrel__Certificates__Default__Path: /https/nerdstore.io-localhost.pfx
    AppSettings__DatabaseType: SqlServer

include:
    - docker-common-resources.yml

services:
    
    nerdstore-database:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: nerdstore-database
        ports:
            - "1433:1433"
        expose:
            - 1433
        environment:
            SA_PASSWORD: "MyDB@123"
            ACCEPT_EULA: "Y"
        healthcheck:
            test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P MyDB@123 -Q 'SELECT 1'" ]
            interval: 3s
            timeout: 5s
            retries: 10
            start_period: 5s

    api-identity:
        image: willianbrito00/nerdstore-api-identity:${TAG}
        container_name: nerdstore-api-identity
        build:
            context: ../../src
            dockerfile: ./services/Identity/NSE.Identity.API/Dockerfile        
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=nerdstore-database,1433;Database=DBUsers;User Id=sa;Password=MyDB@123;TrustServerCertificate=True;"
        volumes:
            - ./certs:/https:ro
        depends_on:
            generate-pfx:
                condition: service_completed_successfully
            nerdstore-database:
                condition: service_started
            rabbitmq:
                condition: service_healthy

    api-cart:
        image: willianbrito00/nerdstore-api-cart:${TAG}
        container_name: nerdstore-api-cart
        build:
            context: ../../src
            dockerfile: ./services/ShoppingCart/NSE.ShoppingCart.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=nerdstore-database,1433;Database=DBShoppingCart;User Id=sa;Password=MyDB@123;TrustServerCertificate=True;"
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started
            nerdstore-database:
                condition: service_started
            rabbitmq:
                condition: service_healthy

    api-catalog:
        image: willianbrito00/nerdstore-api-catalog:${TAG}
        container_name: nerdstore-api-catalog
        build:
            context: ../../src
            dockerfile: ./services/Catalog/NSE.Catalog.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=nerdstore-database,1433;Database=DBCatalog;User Id=sa;Password=MyDB@123;TrustServerCertificate=True;"
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started
            nerdstore-database:
                condition: service_started
            rabbitmq:
                condition: service_healthy

    api-customers:
        image: willianbrito00/nerdstore-api-customers:${TAG}
        container_name: nerdstore-api-customers
        build:
            context: ../../src
            dockerfile: ./services/Customer/NSE.Customer.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=nerdstore-database,1433;Database=DBCustomer;User Id=sa;Password=MyDB@123;TrustServerCertificate=True;"
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started
            nerdstore-database:
                condition: service_started
            rabbitmq:
                condition: service_healthy

    api-order:
        image: willianbrito00/nerdstore-api-order:${TAG}
        container_name: nerdstore-api-order
        build:
            context: ../../src
            dockerfile: ./services/Order/NSE.Order.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=nerdstore-database,1433;Database=DBOrder;User Id=sa;Password=MyDB@123;TrustServerCertificate=True;"
            Logging__Console__FormatterName: ""
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started
            nerdstore-database:
                condition: service_started
            rabbitmq:
                condition: service_healthy

    api-payment:
        image: willianbrito00/nerdstore-api-payment:${TAG}
        container_name: nerdstore-api-payment
        build:
            context: ../../src
            dockerfile: ./services/Payment/NSE.Payment.API/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=nerdstore-database,1433;Database=DBPayment;User Id=sa;Password=MyDB@123;TrustServerCertificate=True;"
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started
            api-order:
                condition: service_started
            nerdstore-database:
                condition: service_started
            rabbitmq:
                condition: service_healthy

    api-bff-checkout:
        image: willianbrito00/nerdstore-api-bff-checkout:${TAG}
        container_name: nerdstore-api-bff-checkout
        build:
            context: ../../src
            dockerfile: ./api-gateways/Checkout/NSE.Bff.Checkout/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=nerdstore-database,1433;Database=DBStatus;User Id=sa;Password=MyDB@123;TrustServerCertificate=True;"
        volumes:
            - ./certs:/https:ro
        depends_on:
            api-identity:
                condition: service_started
            api-cart:
                condition: service_started
            api-payment:
                condition: service_started
            api-order:
                condition: service_started
            nerdstore-database:
                condition: service_started

    web-mvc:
        image: willianbrito00/nerdstore-web-mvc-ecommerce:${TAG}
        container_name: nerdstore-web-mvc-ecommerce
        build:
            context: ../../src
            dockerfile: ./web/MVC/NSE.WebApp.MVC/Dockerfile        
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=nerdstore-database,1433;Database=DBStatus;User Id=sa;Password=MyDB@123;TrustServerCertificate=True;"
            LC_ALL: "en_US.UTF-8"
            LANG: "en_US.UTF-8"
            # Change the two lines above to your culture (ex pt_BR)
            USE_HTTPS_REDIRECTION: "false"
        expose:
            - 80
            - 443
        volumes:
            - ./certs:/https:ro
            - dpkeys:/var/data_protection_keys/
        depends_on:
            api-catalog:
                condition: service_started
            api-identity:
                condition: service_started
            api-customers:
                condition: service_started
            api-bff-checkout:
                condition: service_started
            nerdstore-database:
                condition: service_started

    web-status:
        image: willianbrito00/nerdstore-web-status:${TAG}
        container_name: nerdstore-web-status
        build:
            context: ../../src
            dockerfile: ./web/Status/NSE.WebApp.Status/Dockerfile
        restart: always
        environment:
            <<: *common-variables
            CUSTOMCONNSTR_DefaultConnection: "Server=nerdstore-database,1433;Database=DBStatus;User Id=sa;Password=MyDB@123;TrustServerCertificate=True;"
        volumes:
            - ./certs:/https:ro
            - ./certs/nerdstore.crt:/usr/local/share/ca-certificates/nerdstore.crt
        depends_on:
            api-identity:
                condition: service_started
            nerdstore-database:
                condition: service_started

volumes:
    dpkeys:
    nginx-certs:
