name: Continuous Integration

on:
  push:
    paths:
      - 'global.json'
      - 'src/**'
      - '.github/**'
    branches:
      - main
  pull_request:
    paths:
      - 'global.json'
      - 'src/**'
      - '.github/**'
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # ======================================================
  # 1. Versionamento do Projeto
  # ======================================================
  versioning:
    runs-on: ubuntu-latest
    name: Versioning

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 
      
      - uses:  codacy/git-version@2.8.3
        id: version
        with:
          release-branch: main
          prefix: v

      - name: Repository Tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}"@users.noreply.github.com
          git config --global user.name "${{ github.actor }}"
          git tag -a "${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main'
      
      - name: Create file version
        run: |
          echo ${{ steps.version.outputs.version }} > version.txt
        if: github.ref == 'refs/heads/main'

      - uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt
        if: github.ref == 'refs/heads/main'


  # ======================================================
  # 2. Build e Testes
  # ======================================================
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: versioning

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: ${{ secrets.TEST_DB_SA_PASSWORD }}
        options: --health-cmd="exit 0" --health-interval=10s --health-timeout=5s --health-retries=3
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
        env:
          RABBITMQ_DEFAULT_USER: "nerdstore"
          RABBITMQ_DEFAULT_PASS: ${{ secrets.TEST_RABBITMQ_PASSWORD }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --no-restore --configuration Release --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults"  

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: ./src/TestResults

  # ======================================================
  # 3. Análise de Segurança de Código (SAST)
  # ======================================================
  sast:
    runs-on: ubuntu-latest
    needs: versioning
    name: SAST - Horusec Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SAST - Horusec Run
        run: |
          curl -sL https://raw.githubusercontent.com/Willian-Brito/dev-sec-ops-learning/refs/heads/main/tools/horusec/horusec_docker_linux.sh| bash

      - name: SAST - Horusec Report Generation
        run: |
          cd reports
          curl -sL https://raw.githubusercontent.com/Willian-Brito/dev-sec-ops-learning/refs/heads/main/tools/horusec/horusec_json2md/horusec_json2md.py -o horusec_json2md.py 
          python3 horusec_json2md.py horusec_report.json horusec_report.md       

      - name: SAST - Horusec Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: horusec-report
          path: reports/horusec_report.md

      - name: SAST - Horusec Results In Summary
        run: cat reports/horusec_report.md >> $GITHUB_STEP_SUMMARY

  # ======================================================
  # 4.  Análise de Segurança das Dependências (SCA)
  # ======================================================
  sca:
    needs: versioning
    runs-on: ubuntu-latest
    name: SCA - Dependency Check Scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Java (required for Dependency-Check)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run OWASP Dependency-Check
        
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: '${{ github.repository }}'
          path: '.'
          format: 'SARIF'          
          out: 'reports'
          args: |   
            --format HTML           
            --scan .
            --enableRetired
        env:
          JAVA_HOME: /opt/jdk

      - name: Upload vulnerability report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html

  # ======================================================
  # 5. Análise de Segurança de Infra como Código (IaC)
  # ======================================================
  iac:
    needs: versioning
    runs-on: ubuntu-latest
    name: IaC - Kics Scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Kics Scan
        uses: checkmarx/kics-github-action@v2.1.13
        with:          
          path: '.'
          ignore_on_exit: results
          output_path: reports/
          output_formats: 'sarif'

      - name: Display kics results
        run: |
          cat reports/results.sarif

      - name: Upload vulnerability report        
        uses: actions/upload-artifact@v4
        with:
          name: kics-report
          path: reports/
  
  # ======================================================
  # 6. Build das Imagens Docker
  # ======================================================
  docker-build-images:
    name: Build Docker Image Services
    runs-on: ubuntu-latest
    needs: [versioning, build-and-test]

    env:
      TAG: ${{ needs.versioning.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker images
        working-directory: ./infra/docker
        run: |
          docker compose -f ./docker-compose-ci.yml build --parallel

      - name: Export images to TAR
        run: |
          docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-identity:${{env.TAG}} -o api-identity.tar
          docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-cart:${{env.TAG}} -o api-cart.tar
          docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-catalog:${{env.TAG}} -o api-catalog.tar
          docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-customers:${{env.TAG}} -o api-customers.tar
          docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-order:${{env.TAG}} -o api-order.tar
          docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-payment:${{env.TAG}} -o api-payment.tar
          docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-bff-checkout:${{env.TAG}} -o api-bff-checkout.tar
          docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-web-mvc-ecommerce:${{env.TAG}} -o web-mvc.tar
          docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-web-status:${{env.TAG}} -o web-status.tar

      - name: Listing (Debug)
        run: |
          pwd
          ls -la
          find . -name "*.tar"

      - name: Upload docker images artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-${{ env.TAG }}
          path: |
            api-identity.tar
            api-cart.tar
            api-catalog.tar
            api-customers.tar
            api-order.tar
            api-payment.tar
            api-bff-checkout.tar
            web-mvc.tar
            web-status.tar

  # ======================================================
  # 7. Analise de Segurança da Imagem Docker
  # ======================================================
  container-scan:
    needs: [versioning, docker-build-images]
    runs-on: ubuntu-latest
    name: Container Scan - Trivy Scan Docker Images

    env:
      TAG: ${{ needs.versioning.outputs.version }}

    steps:
      - name: Download Docker images artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-images-${{ env.TAG }}
          path: .

      - name: List files
        run: ls -la images

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Load Docker images
        run: |
          docker load -i api-identity.tar
          docker load -i api-cart.tar
          docker load -i api-catalog.tar
          docker load -i api-customers.tar
          docker load -i api-order.tar
          docker load -i api-payment.tar
          docker load -i api-bff-checkout.tar
          docker load -i web-mvc.tar
          docker load -i web-status.tar

      - name: Run Trivy Scan Images
        run: |
          mkdir trivy-reports

          trivy image --severity HIGH,CRITICAL --format table -o trivy-reports/api-identity.txt ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-identity:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --format table -o trivy-reports/api-cart.txt ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-cart:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --format table -o trivy-reports/api-catalog.txt ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-catalog:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --format table -o trivy-reports/api-customers.txt ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-customers:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --format table -o trivy-reports/api-order.txt ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-order:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --format table -o trivy-reports/api-payment.txt ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-payment:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --format table -o trivy-reports/api-bff-checkout.txt ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-bff-checkout:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --format table -o trivy-reports/web-mvc.txt ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-web-mvc-ecommerce:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --format table -o trivy-reports/web-status.txt ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-web-status:${{ env.TAG }}
      
      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: trivy-reports

  # ======================================================
  # 8. Push das Imagens para o Docker Hub
  # ======================================================
  docker-push:
    needs: [versioning, container-scan]
    runs-on: ubuntu-latest
    name: Push Docker Images

    env:
      VERSION: ${{ needs.versioning.outputs.version }}
      DOCKER_REPO: ${{ vars.DOCKERHUB_REPOSITORY }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-images-${{ env.VERSION }}
          path: .

      - name: Load Docker images
        run: |
          docker load -i api-identity.tar
          docker load -i api-cart.tar
          docker load -i api-catalog.tar
          docker load -i api-customers.tar
          docker load -i api-order.tar
          docker load -i api-payment.tar
          docker load -i api-bff-checkout.tar
          docker load -i web-mvc.tar
          docker load -i web-status.tar

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Latest (only main)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $DOCKER_REPO/nerdstore-api-identity:$VERSION $DOCKER_REPO/nerdstore-api-identity:latest
          docker tag $DOCKER_REPO/nerdstore-api-cart:$VERSION $DOCKER_REPO/nerdstore-api-cart:latest
          docker tag $DOCKER_REPO/nerdstore-api-catalog:$VERSION $DOCKER_REPO/nerdstore-api-catalog:latest
          docker tag $DOCKER_REPO/nerdstore-api-customers:$VERSION $DOCKER_REPO/nerdstore-api-customers:latest
          docker tag $DOCKER_REPO/nerdstore-api-order:$VERSION $DOCKER_REPO/nerdstore-api-order:latest
          docker tag $DOCKER_REPO/nerdstore-api-payment:$VERSION $DOCKER_REPO/nerdstore-api-payment:latest
          docker tag $DOCKER_REPO/nerdstore-api-bff-checkout:$VERSION $DOCKER_REPO/nerdstore-api-bff-checkout:latest
          docker tag $DOCKER_REPO/nerdstore-web-mvc-ecommerce:$VERSION $DOCKER_REPO/nerdstore-web-mvc-ecommerce:latest
          docker tag $DOCKER_REPO/nerdstore-web-status:$VERSION $DOCKER_REPO/nerdstore-web-status:latest
          
      - name: Push Version Tags
        run: |
          docker push $DOCKER_REPO/nerdstore-api-identity:$VERSION
          docker push $DOCKER_REPO/nerdstore-api-cart:$VERSION
          docker push $DOCKER_REPO/nerdstore-api-catalog:$VERSION
          docker push $DOCKER_REPO/nerdstore-api-customers:$VERSION
          docker push $DOCKER_REPO/nerdstore-api-order:$VERSION
          docker push $DOCKER_REPO/nerdstore-api-payment:$VERSION
          docker push $DOCKER_REPO/nerdstore-api-bff-checkout:$VERSION
          docker push $DOCKER_REPO/nerdstore-web-mvc-ecommerce:$VERSION
          docker push $DOCKER_REPO/nerdstore-web-status:$VERSION
            
      - name: Push Latest Tags
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $DOCKER_REPO/nerdstore-api-identity:latest
          docker push $DOCKER_REPO/nerdstore-api-cart:latest
          docker push $DOCKER_REPO/nerdstore-api-catalog:latest
          docker push $DOCKER_REPO/nerdstore-api-customers:latest
          docker push $DOCKER_REPO/nerdstore-api-order:latest
          docker push $DOCKER_REPO/nerdstore-api-payment:latest
          docker push $DOCKER_REPO/nerdstore-api-bff-checkout:latest
          docker push $DOCKER_REPO/nerdstore-web-mvc-ecommerce:latest
          docker push $DOCKER_REPO/nerdstore-web-status:latest