name: Continuous Integration

on:
  push:
    paths:
      - 'global.json'
      - 'src/**'
      - '.github/**'
    branches:
      - main
  pull_request:
    paths:
      - 'global.json'
      - 'src/**'
      - '.github/**'
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # ======================================================
  # 1. Versionamento do Projeto
  # ======================================================
  versioning:
    runs-on: ubuntu-latest
    name: Versioning

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 
      
      - uses:  codacy/git-version@2.8.3
        id: version
        with:
          release-branch: main
          prefix: v

      - name: Repository Tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}"@users.noreply.github.com
          git config --global user.name "${{ github.actor }}"
          git tag -a "${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main'
      
      - name: Create file version
        run: |
          echo ${{ steps.version.outputs.version }} > version.txt
        if: github.ref == 'refs/heads/main'

      - uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt
        if: github.ref == 'refs/heads/main'


  # ======================================================
  # 2. Build e Testes
  # ======================================================
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: versioning

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: ${{ secrets.TEST_DB_SA_PASSWORD }}
        options: --health-cmd="exit 0" --health-interval=10s --health-timeout=5s --health-retries=3
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
        env:
          RABBITMQ_DEFAULT_USER: "nerdstore"
          RABBITMQ_DEFAULT_PASS: ${{ secrets.TEST_RABBITMQ_PASSWORD }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --no-restore --configuration Release --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults"  

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: ./src/TestResults
  
  # ======================================================
  # 3. Build das Imagens Docker
  # ======================================================
  docker-build-images:
    name: Build Docker Image Services
    runs-on: ubuntu-latest
    needs: [versioning, build-and-test]

    env:
      TAG: ${{ needs.versioning.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set TAG env for compose
      #   run: echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Listing (Debug)
        run: ls -la

      - name: Build docker images
        working-directory: ./infra/docker
        run: |
          docker compose -f ./docker-compose-ci.yml build --parallel

      # - name: Export images to TAR
      #   run: |
      #     docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-identity:${{env.TAG}} -o api-identity.tar
      #     docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-cart:${{env.TAG}} -o api-cart.tar
      #     docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-catalog:${{env.TAG}} -o api-catalog.tar
      #     docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-customers:${{env.TAG}} -o api-customers.tar
      #     docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-order:${{env.TAG}} -o api-order.tar
      #     docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-payment:${{env.TAG}} -o api-payment.tar
      #     docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-api-bff-checkout:${{env.TAG}} -o api-bff-checkout.tar
      #     docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-web-mvc-ecommerce:${{env.TAG}} -o web-mvc.tar
      #     docker save ${{vars.DOCKERHUB_REPOSITORY}}/nerdstore-web-status:${{env.TAG}} -o web-status.tar

      - name: Export all compose images
        run: |
          docker images --format "{{.Repository}}:{{.Tag}}" | grep willianbrito00 > images.txt

          while read image; do
            name=$(echo $image | tr '/:' '_')
            docker save $image -o "$name.tar"
          done < images.txt

      - name: Upload docker images artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-${{ env.TAG }}
          path: |
            api-identity.tar
            api-cart.tar
            api-catalog.tar
            api-customers.tar
            api-order.tar
            api-payment.tar
            api-bff-checkout.tar
            web-mvc.tar
            web-status.tar